# Generated by Django 3.1.7 on 2021-04-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210331_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
